version: '3'

services:
  web: &web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
      - bundle:/usr/local/bundle
    env_file: .env
    depends_on:
      - redis
      - db
    tty: true
    stdin_open: true

  spring:
    <<: *web
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    tty: false
    stdin_open: false

  worker:
    <<: *web
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    ports: []

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:11.3
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  bundle:
  dbdata:

